install-tools:
	go get golang.org/x/tools/cmd/goimports \
        github.com/twitchtv/retool \
        github.com/golang/protobuf/protoc-gen-go \
        github.com/twitchtv/twirp/protoc-gen-twirp \
        github.com/golang/mock/gomock \
        github.com/golang/mock/mockgen \
        golang.org/x/lint/golint \
        github.com/golangci/golangci-lint/cmd/golangci-lint

import-images:
	./gitlab/import-images.sh
